#!/bin/tcsh

set VERSION=0.0.1

echo "Creating TGZ & RPM version ${VERSION}"
make dist

if (!(-f pspmovie.tar.gz)) then
	exit(-1)
endif
echo repacking ....
tar xzf pspmovie.tar.gz
/bin/rm -rf "pspmovie-${VERSION}"
mv pspmovie "pspmovie-${VERSION}"
/bin/rm pspmovie.tar.gz

tar cf - "pspmovie-${VERSION}" | bzip2 -c > "pspmovie-${VERSION}.tar.bz2"

if (!(-f "pspmovie-${VERSION}.tar.bz2")) then
	echo "Something fcked up: pspmovie-${VERSION}.tar.bz2 doesn't created"
	exit(-1)
endif

/bin/rm -rf "pspmovie-${VERSION}"
