#!/bin/tcsh

set VERSION=0.0.1

echo "Creating TGZ & RPM version ${VERSION}"
make dist

if (!(-f pspmovie.tar.gz)) then
	exit(-1)
endif
echo repacking ....
tar xzf pspmovie.tar.gz
/bin/rm -rf "pspmovie-${VERSION}"
mv pspmovie "pspmovie-${VERSION}"
/bin/rm pspmovie.tar.gz

/bin/cp README TODO COPYING ChangeLog "pspmovie-${VERSION}"
tar cf - "pspmovie-${VERSION}" | gzip -c > "pspmovie-${VERSION}.tar.gz"

if (!(-f "pspmovie-${VERSION}.tar.gz")) then
	echo "Something fcked up: pspmovie-${VERSION}.tar.gz doesn't created"
	exit(-1)
endif

/bin/rm -rf "pspmovie-${VERSION}"
